// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwcA2Yjjj9cr5uv8IEEqJx_EsqNbmjmDE',
    appId: '1:890291890968:web:9bba904eb0b376dd3c8c6d',
    messagingSenderId: '890291890968',
    projectId: 'greenage-941bc',
    authDomain: 'greenage-941bc.firebaseapp.com',
    storageBucket: 'greenage-941bc.firebasestorage.app',
    measurementId: 'G-FK361CLJT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEl_mffaaTYwbtxsbNSyTO5MB1qt_56-o',
    appId: '1:890291890968:android:9976dd711439ae133c8c6d',
    messagingSenderId: '890291890968',
    projectId: 'greenage-941bc',
    storageBucket: 'greenage-941bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGT0wWeVCu9y03WGdWztI4TNryGdHkvNE',
    appId: '1:890291890968:ios:bfd4e10a08f867223c8c6d',
    messagingSenderId: '890291890968',
    projectId: 'greenage-941bc',
    storageBucket: 'greenage-941bc.firebasestorage.app',
    iosBundleId: 'com.greenage.greenageEcomm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGT0wWeVCu9y03WGdWztI4TNryGdHkvNE',
    appId: '1:890291890968:ios:bfd4e10a08f867223c8c6d',
    messagingSenderId: '890291890968',
    projectId: 'greenage-941bc',
    storageBucket: 'greenage-941bc.firebasestorage.app',
    iosBundleId: 'com.greenage.greenageEcomm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwcA2Yjjj9cr5uv8IEEqJx_EsqNbmjmDE',
    appId: '1:890291890968:web:b9c0b8379af8c5cb3c8c6d',
    messagingSenderId: '890291890968',
    projectId: 'greenage-941bc',
    authDomain: 'greenage-941bc.firebaseapp.com',
    storageBucket: 'greenage-941bc.firebasestorage.app',
    measurementId: 'G-WTQXHK172W',
  );
}
